# Generated by Django 5.0.3 on 2024-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunos",
            name="RA",
            field=models.CharField(max_length=11),
        ),
    ]
