# Generated by Django 5.0.3 on 2024-03-26 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("email", models.CharField(max_length=200)),
                ("disciplina", models.CharField(max_length=100)),
                ("aula", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
